### ISSUE TITLE
mac の Java11 マイグレーション時にでSSL例外がでる？

### ISSUE THREAD

**Issue by ajiyoshi-vg** [voyagegroup/hakaru#10]
```bash
$ java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

```
$ make init migrate info
Thu Nov 08 15:12:41 JST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Thu Nov 08 15:12:41 JST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Thu Nov 08 15:12:42 JST 2018 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:624)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2249)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4232)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:71)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1173)
	at org.flywaydb.core.Flyway.init(Flyway.java:970)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
	at org.flywaydb.commandline.Main.main(Main.java:88)


** END NESTED EXCEPTION **


Thu Nov 08 15:12:42 JST 2018 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:624)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2249)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4232)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1472)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:71)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1174)
	at org.flywaydb.core.Flyway.init(Flyway.java:970)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
	at org.flywaydb.commandline.Main.main(Main.java:88)


** END NESTED EXCEPTION **


make[1]: *** [__flyway] Error 1
make: *** [init] Error 2

```

**Comment by katzchang** [comment]
いったんdockerで

**Comment by katzchang** [comment]
あー、↑のやつ、もともとdockerで実行してたのかな。
`javax.net.ssl.SSLException` でがちで、certs追加したりいろいろしないと動かないっぽい。
今回つかったmavenイメージは、そのへんむしするようになってるっていうちょっと乱暴なやつです。
